---
# This named task uses the Ansible template module to generate the a
# part of the MDF configuration. Once it is done it stores the result
# in a file
- name: Building MDF configuration
  template: >
    src=main.conf.j2
    dest={{ build_dir }}/mdf.conf.part
