model: EX4300-48T
host: SWLNG001A01A
role: idf
interface:
  vlan_mgmt:
    ip: 10.1.1.8
  trunks:
    - name: ae0
      type: uplink
      peer: MDF3A
      agg:
        - ge-0/0/0
        - ge-0/0/1
    - name: ge-0/0/47
      type: downlink
      peer: IDF1B 
      vlans:
        - CBP_USERS
        - CBP_MGMT
  access:
    range:
      - name: range1
        prefix: ge-0/0
        start_port: 1
        end_port: 30
        vlan: CBP_USERS
        poe: voip
      - name: range2
        prefix: ge-0/0
        start_port: 31
        end_port: 45
        vlan: CBP_USERS
    single:
      - name: ge-0/0/46
        vlan: CBP_USERS
        poe: on
vlans:
  - CBP_USERS
  - CBP_MGMT
  - CBP_VOIP
