model: EX4300-48T
host: SWLNG001A03B
interface:
  vlan_mgmt:
    ip: 10.1.1.14
  trunks:
    - name: ge-0/0/0
      type: uplink
      peer: MDF3A
  access:
    range:
      - name: range1
        prefix: ge-0/0
        start_port: 1
        end_port: 30
        vlan: CBP_USERS
      - name: range2
        prefix: ge-0/0
        start_port: 31
        end_port: 45
        vlan: CBP_USERS
        poe: default
    single:
      - name: ge-0/0/46
        vlan: CBP_USERS
vlans:
  - CBP_USERS
  - CBP_MGMT
  - CBP_VOIP
