model: EX4550-32F
host: SWLNG001A03A
role: mdf
interface:
  loop_mgmt:
    ip: 10.1.1.6
  uplinks:
    - name: ge-0/0/0
      ip: 10.113.10.4
      mask: 28
      peer: RLNG00AV001A
    - name: ge-0/0/31
      ip: 10.113.10.33
      mask: 28
      peer: RLNG00VV001A
  trunks:
    - name: ae1
      type: downlink
      peer: IDF1A
      vlans:
        - CBP_USERS
        - CBP_MGMT
        - CBP_VOIP
      agg:
        - ge-0/0/1
        - ge-0/0/4
    - name: ae2
      type: downlink
      peer: IDF2A
      vlans:
        - CBP_USERS
        - CBP_MGMT
        - CBP_VOIP
      agg:
        - ge-0/0/2
        - ge-0/0/5
    - name: ge-0/0/3
      type: downlink
      peer: IDF3B
      vlans:
        - CBP_USERS
        - CBP_MGMT
        - CBP_VOIP
  access:
    range:
      - name: range1
        prefix: ge-0/0
        start_port: 4
        end_port: 9
        vlan: CBP_SERVERS
    single:
      - name: ge-0/0/12
        vlan: CBP_USERS
        voip: voip
